//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace EzBiologyy.Pages
{
    public partial class TakeQuiz
    {

        /// <summary>
        /// quizTitleLbl control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label quizTitleLbl;


        /// <summary>
        /// questionRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater questionRepeater;


        /// <summary>
        /// questionIDHidden control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField questionIDHidden;


        /// <summary>
        /// questionTypeHidden control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField questionTypeHidden;


        /// <summary>
        /// mcqPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel mcqPanel;


        /// <summary>
        /// optionList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButtonList optionList;


        /// <summary>
        /// fillPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel fillPanel;


        /// <summary>
        /// answerTextbox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox answerTextbox;


        /// <summary>
        /// submitBtn control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button submitBtn;

    }
}